export const site = {
  name: 'AFTERSTORY',
  instagram: 'https://www.instagram.com/wearafterstory/',
  skipLink: 'Skip to content',
  newTab: ' (opens in a new tab)',
  header: {
    category: 'Independent fragrance', chapter: 'The first chapter', country: 'India',
    tagline: 'Made to be remembered.', status: 'Launching soon',
  },
  introduction: {
    eyebrow: 'A new story in scent',
    headline: 'Some moments', continuation: 'stay ', emphasis: 'with you.',
    description: 'Scents for the moments you keep thinking about.',
    supporting: 'Unisex fragrances. A story that becomes yours.',
    follow: 'Follow us on Instagram', followAccessible: '',
    updates: 'Launching soon. Follow @wearafterstory for updates.',
    number: '01 /', note: 'Every scent begins a story.',
  },
  campaign: {
    src: '/images/lucknow-campaign.webp', width: 1122, height: 1402,
    alt: 'A clear AFTERSTORY perfume bottle with a visible atomizer tube by a window overlooking a Lucknow-inspired riverfront. A new chapter. Unmistakably yours. The first chapter. Coming soon.',
    caption: 'The first chapter is almost here.', credit: 'AFTERSTORY / Prelude',
  },
  launch: {
    eyebrow: 'First release',
    heading: 'Three scents to begin with.',
    intro: 'The first AFTERSTORY release opens with clean brightness, warm tobacco, and soft musk. Each bottle is blended in small batches at 25% w/w.',
    cta: 'Message us on Instagram',
    note: 'Limited first batches. Prepaid orders only.',
    scents: [
      {
        code: '03',
        name: 'FIRST LIGHT',
        profile: 'Citrus / Green Florals / Clean Woods',
        story: 'First light, finding its way through quiet mornings.',
        mood: 'Clean, bright, everyday.',
        price: '₹499',
      },
      {
        code: '02',
        name: 'TOBACCO BLOOM',
        profile: 'Tobacco / Vanilla / Warm Woods',
        story: 'Tobacco bloom, lingering softly after the evening ends.',
        mood: 'Warm, rounded, evening.',
        price: '₹499',
      },
      {
        code: '06',
        name: 'WHITE MUSK',
        profile: 'Powder / White Florals / Musk',
        story: 'White musk, resting softly against warm bare skin.',
        mood: 'Soft, intimate, clean.',
        price: '₹499',
      },
    ],
  },
  footer: { copyright: '2026 AFTERSTORY', thought: 'The moment ends. The story stays.', social: 'Instagram' },
  metadata: {
    url: 'https://www.afterstory.in',
    title: 'AFTERSTORY Perfumes India | Independent Unisex Fragrances',
    description: 'AFTERSTORY is an independent Indian perfume brand creating unisex fragrances made to be remembered. The first chapter is launching soon.',
    socialDescription: 'Discover AFTERSTORY, an independent Indian perfume brand creating unisex fragrances made to be remembered.',
    twitterDescription: 'AFTERSTORY unisex perfumes. Made to be remembered. Launching soon in India.',
  },
} as const;
